spring:
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/fitness
    username: root
    password: 2544
  # 文件/请求上传大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

# mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


# 阿里云oss
aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    bucketName: tlias-springboot1

#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

#swagger接口文档
knife4j:
  enable: true
  title: 健身打卡接口文档
  description: "健身打卡接口文档描述"
  version: 1.0.0
  contact:
    name: candy
    url: https://www.example.com
    email: author@example.com
  terms-of-service: https://www.example.com/terms
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT




#knife4j:
#  enable: true
#  openapi:
#    title: 健身打卡接口文档
#    description: "健身打卡接口文档"
#    email: zhanghuyi@itcast.cn
#    concat: candy
#    url: https://www.itcast.cn
#    version: v1.0.0
#    group:
#      default:
#        group-name: default
#        api-rule: package
#        api-rule-resources:
#          - com.itheima.mp.controller